#!/bin/sh

if fgrep -q rd.debug /proc/cmdline; then
  set -x
fi

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

exec </dev/console >/dev/console 2>&1

if fgrep -q rd.break /proc/cmdline; then
  exec /bin/sh
fi

for arg in $(cat /proc/cmdline); do
  case $arg in
    modules=*)
      KOPT_modules="${arg#modules=}";;
    root=*)
      KOPT_root="${arg#root=}";;
    rootdelay=*)
      KOPT_rootdelay="${arg#rootdelay=}";;
  esac
done

if [ -z "$KOPT_root" ]; then
  echo "Missing root= parameter!"
  exec sh
fi

for m in $(echo "$KOPT_modules" | tr ',' ' '); do
  modprobe "$m"
done

[ -n "$KOPT_rootdelay" ] && sleep "$KOPT_rootdelay"

# Mount permanent rootfs
mkdir -p /sysroot
mount "$KOPT_root" /sysroot

# Leave initrd
exec switch_root /sysroot /sbin/init

# Ruh-roh
echo "Failed to mount root filesystem!"
exec sh
